### ISSUE TITLE
INTERNAL APPLICATION ERROR

### ISSUE THREAD

**Issue by King-GO** [andrzejkupczyk/mantisbt-todolists#38]
MantisBT Version | 2.26.0-dev
PHP Version | 7.3.12
Database Version, Description | 10.4.10, 10.4.10-MariaDB

update to version 3, 

execute 
`composer install --no-dev`
then,

INTERNAL APPLICATION ERROR

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

**Comment by andrzejkupczyk** [comment]
Thanks, I'm on it!

**Comment by andrzejkupczyk** [comment]
@ King-GO I am eager to help but need more information. I'm afraid I can't reproduce this error.

Did the `composer install --no-dev` command work correctly? What's the output?

Is there any additional information available under the title of the error?

**Comment by andrzejkupczyk** [comment]
@King-GO , I am eager to help but need more information. I'm afraid I can't reproduce this error.

Did the `composer install --no-dev` command work correctly? What's the output?

Is there any additional information available under the title of the error?

**Comment by King-GO** [comment]
`Verifying lock file contents can be installed on current platform.
Package operations: 2 installs, 0 updates, 0 removals
    0 [>---------------------------]    0 [->--------------------------]
  - Installing composer/installers (1.x-dev 894a0b5): Extracting archive
  - Installing webgarden/mantisbt-termite (dev-main 7fcb13f): Extracting archive

Generating optimized autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!`

tested on v.2.5 is OK, but failed on v.3.

**Comment by cmuerau** [comment]
Same error message here, but different setup.

MantisBT version: 2.25.5
PHP version: 8.0 (just switched from 7.4)

Just pulled latest commits.

Disabled plugin completely via FTP as MantisBT GUI only showed error message no regard which button was clicked.

For separation purposes I use multiple MantisBT installations, happened in all of them.

**Comment by andrzejkupczyk** [comment]
I will look into it asap

**Comment by andrzejkupczyk** [comment]
@King-GO , @cmuerau , could you please specify exactly how did you upgrade the plugin?  
I have followed different steps but still haven't been able to reproduce the error. Each method upgraded the plugin to the latest version:

<details><summary>Using Git commands</summary>

  1. `git clone`
  2. `git checkout` release [v2.5.0](https://github.com/andrzejkupczyk/mantisbt-todolists/releases/tag/v2.5.0)
  3. Install the plugin
  4. `git checkout` release [v3.0.0](https://github.com/andrzejkupczyk/mantisbt-todolists/releases/tag/v3.0.0)
  5. `composer install --no-dev`

</details>

<details><summary>Using ZIP archive</summary>

  1. Download and unzip [v2.5.0](https://github.com/andrzejkupczyk/mantisbt-todolists/archive/refs/tags/v2.5.0.zip)
  2. Install the plugin
  4. Download and unzip [v3.0.0](https://github.com/andrzejkupczyk/mantisbt-todolists/archive/refs/tags/v3.0.0.zip) (overwrite old pugin's files)
  5. `composer install --no-dev`

</details>

<details><summary>Using composer installers</summary>

  1. Download and unzip [v2.5.0](https://github.com/andrzejkupczyk/mantisbt-todolists/archive/refs/tags/v2.5.0.zip)
  2. Install the plugin
  3. Run `composer require andrzejkupczyk/mantis-todolists` in the MantisBT root directory

</details>

**Comment by King-GO** [comment]
I'm using Zip archive method 2

**Comment by cmuerau** [comment]
Method 1: git pull origin on 

Additional information: PHP Version 7.4.30 / Shared Hosting

**Comment by fcolella** [comment]
Hi guys, any update on this issue?
Does this plugin require PHP 8?

This is the error Im getting:

<img width="527" alt="2022-12-29 11_28_49-Manage Plugins - MantisBT" src="https://user-images.githubusercontent.com/15364953/209967695-d991087a-4fd2-431d-95ae-34caec34aa1e.png">

MantisBT Version | 2.25.2
PHP Version | 7.3.11

thanx!

**Comment by andrzejkupczyk** [comment]
Thank you, @fcolella. I couldn't reproduce this error but will get back to it ASAP.

**Comment by andrzejkupczyk** [comment]
Okay, so apparently I put too much trust in automated refactoring. I'll get back to you guys after the patch is released.

**Comment by cmuerau** [comment]
Downloaded latest version via git methode and still get the same "Internal Application Error" message. @andrzejkupczyk

Thanks for trying and happy new year!

**Comment by andrzejkupczyk** [comment]
In that case, I closed the issue prematurely 😉 Thank you for verifying.

**Comment by andrzejkupczyk** [comment]
Ok dears, so I checked _everything_ again and made some minor changes. Thanks for your invaluable help.

I had to publish [a completely new release](https://github.com/andrzejkupczyk/mantisbt-todolists/releases/tag/v3.0.1) and clean up the Packagist registry (there were two packages: `andrzejkupczyk/mantisbt-todolists` and `webgarden/mantisbt-todolists`).

Now, at least for me, it works. I have tried both installation methods listed in the [README.md](https://github.com/andrzejkupczyk/mantisbt-todolists/blob/v3.0.1/README.md) file.

If it turns out that the problem still occurs, please make sure that the plugin is in the correct version after installation ([ToDoLists.php#L18](https://github.com/andrzejkupczyk/mantisbt-todolists/blob/v3.0.1/ToDoLists.php#L18)). If it is not, then something is wrong with the installation process. Otherwise I would need further assistance :(

MantisBT version: 2.25.5
PHP version: 7.0.33 (switched from 8.0, just to be shure)

**Comment by andrzejkupczyk** [comment]
@cmuerau, don't worry, there's no way I'm leaving you like this :) Composer isn't something that needs to be "installed" in your shared hosting environment. It is simply an executable phar file that can be uploaded to the server, much like the plugins themselves.

I could include `composer.phar` in the plugin's repository but I'm not sure if that would be helpful?

**Comment by cmuerau** [comment]
@andrzejkupczyk Your made my day, you are my hero for today!

I wasn't aware of the fact that composer ...
- can be installed on a per-directory basis
- can be installed by non-root users

Installation from getcomposer.org worked like a charm, and 5 minutes later a H2 from digitalocean.com regarding the syntax for PHAR files was read and understood.

Your plugin works again in my main installation without any error message. I also discovered that is has been linked to the snippets plugin content which I also use a LOT! Together this two will positively boost my options a lot!

So, thank you again for all your help to get the plugin up and running again 🌞

**Comment by fcolella** [comment]
Hi @andrzejkupczyk 
It works! thank you so much, your plugin is great!

**Comment by andrzejkupczyk** [comment]
Excellent! Thank you for your feedback 🤝
