### ISSUE TITLE
Login page crashes when plugin is enabled

### ISSUE THREAD

**Issue by choeft** [andrzejkupczyk/mantisbt-todolists#39]
Hi there,

the Login page gives me an WSOD when plugin is enabled. After deinstallation, everything goes back to normal

Mantis: 2.25.4
Plugin: 3.0.0
PHP: 8.1.10

Logged in Users experience no problems

**Comment by andrzejkupczyk** [comment]
Thanks, @choeft! I just [released patch](https://github.com/andrzejkupczyk/mantisbt-todolists/releases/tag/3.0.1) that should fix issue reported by you.
