### ISSUE TITLE
Problem to change values on the configuration page

### ISSUE THREAD

**Issue by ducemmanuel** [andrzejkupczyk/mantisbt-todolists#4]
Hello,

When I try to change the level to manage or preview data, the system is never updated, and alway the value is automaticaly set to viewer ???

Can you help me.
Thanks
Emmanuel

**Comment by andrzejkupczyk** [comment]
Hey @ducemmanuel, thanks for reporting this issue.
I will try to fix this as soon as I find a moment.

**Comment by andrzejkupczyk** [comment]
Just released [v1.2.0](https://github.com/andrzejkupczyk/mantisbt-todolists/releases/tag/v1.2.0) which solves this issue.

**Comment by ducemmanuel** [comment]
Hello,
I try, it works well.
Thanks for your support.
