### ISSUE TITLE
French support

### ISSUE THREAD

**Issue by Timothy-Anders0n** [andrzejkupczyk/mantisbt-todolists#42]
Hey there,

I wouldn't be considering using MantisBT if your plugin didn't exist, so I thought I'd contribute at least with what I can do. Here's the translation of your strings_lang.txt file for the French language.

Cheers.
[strings_french.txt](https://github.com/andrzejkupczyk/mantisbt-todolists/files/11256858/strings_french.txt)

**Comment by andrzejkupczyk** [comment]
Vive la France! Thanks for contributing.
