### ISSUE TITLE
Compatibility with MantisBT 'master-2.24'

### ISSUE THREAD

**Issue by kremerkp** [andrzejkupczyk/mantisbt-todolists#5]
The version cannot be installed on actual MantisBT Version.

**Comment by andrzejkupczyk** [comment]
Kindly check newly released version https://github.com/andrzejkupczyk/mantisbt-todolists/releases/tag/v2.0.0. Tested with the latest MantisBT version. Thank you.

**Comment by kremerkp** [comment]
works perfect, thx
