### ISSUE TITLE
Plugin doesn't work on MantisBT 2.26.0 :(

### ISSUE THREAD

**Issue by Genisys-Matt** [andrzejkupczyk/mantisbt-todolists#50]
**Describe the bug**
The Plugin doesn't allow you to add things to a list on 2.26.0. The plugin box shows, and you can enter text, but clicking "Add" or hitting Enter doesn't add anything.

**To Reproduce**
Try to add something to a list on 2.26.0

**Expected behavior**
The entered text should add to the list.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - MantisBT version: 2.26.0
 - Plugin version: 3.0.2
 - Database: 10.5.23, 10.5.23-MariaDB
 - PHP 8.1.26

**Additional context**
N/A

**Comment by Genisys-Matt** [comment]
After doing a bit of digging in the logs, I found these:

`2024-01-03 14:47:00 | Error | 81.137.221.179 | 500 | POST /api/rest/plugins/ToDoLists/tasks HTTP/1.0 |   |   | 1.53 K | Apache SSL/TLS access`

`2024-01-03 14:47:00 | Error | 81.137.221.179 |   | [core:alert] .../api/rest/.htaccess: Invalid command 'CGIPassAuth', perhaps misspelled or defined by a module not included in the server configuration, referer: https://<our_domain>/view.php?id=251 |   |   |   | Apache error`

So I went to /api/rest/.htaccess

It mentions this - https://mantisbt.org/bugs/view.php?id=26365 and has this setting: 'CGIPassAuth On'

I tried commenting out the 'CGIPassAuth On' code.

The Plugin now works as before. :)

**Comment by andrzejkupczyk** [comment]
I really appreciate the effort you put into gathering all the details. It's absolutely fantastic to hear that you took the initiative to investigate and resolve the issue on your own! You did a great job! 🤝
