### ISSUE TITLE
SQL Type Boolean Error on Postgres

### ISSUE THREAD

**Issue by madanprabhud** [andrzejkupczyk/mantisbt-todolists#7]
Changed the line 63 of ToDoLists.php

  finished L DEFAULT \'f\''

It's installed on mantis. But, we couldn't able to edit or update the tasks.

Only it adds the task and it's automatically it strikes the test and even we can't delete it.

**Comment by andrzejkupczyk** [comment]
Thanks. This regards latest release I suppose?

**Comment by andrzejkupczyk** [comment]
Good news, @madanprabhud. I manage to fix this nasty bug.
Kindly upgrade plugin using version tagged with [v2.0.1](https://github.com/andrzejkupczyk/mantisbt-todolists/releases/tag/v2.0.1).
Once again, thanks for reporting this issue.
