### ISSUE TITLE
plugin is not functional 

### ISSUE THREAD

**Issue by King-GO** [andrzejkupczyk/mantisbt-todolists#9]
To-do lists: Configuration
Set
Manage: Updater
View: Updater

user role for all projects are Updater, there is no problem with this plugin.
but
when the user in some projects are Reporter, the rest of projects are Updater, the ToDoLists is not shows in those projects with Updater role.

**Comment by andrzejkupczyk** [comment]
Thank you. In fact, the problem was that plugin was checking a user's global permission level instead of a project level permission.
This should be fixed in the latest release [v2.0.3](https://github.com/andrzejkupczyk/mantisbt-todolists/releases/tag/v2.0.3).
